# Localised strings (English & Persian)
STRINGS = {
    "en": {
        "welcome": "👋 Welcome to XHTTP Bot!\n\nUse /link to connect your XHTTP account.",
        "not_linked": "❌ You are not linked. Use /link first.",
        "already_linked": "✅ You are already linked as `{}`. Use /unlink to change.",
        "link_success": "✅ Linked to `{}`.",
        "unlink_success": "✅ Unlinked.",
        "no_servers": "⚠️ No servers configured. Contact admin.",
        "servers_list": "🖥 **Monitored servers:**\n{}",
        "language_changed": "✅ Language set to English.",
        "usage_header": "📊 **Usage for `{}`**\n",
        "no_account": "❌ No account found.",
        "error": "⚠️ Error: {}",
        "status_active": "✅ Active",
        "status_suspended": "⏸️ Suspended",
        "status_revoked": "🚫 Revoked/Expired",
        "data_label": "Data: {} `{:.1f} GB / {:.1f} GB` ({:.1f}%)",
        "data_unlimited": "Data: ♾️ Unlimited",
        "days_left": "Days left: 📅 {} days",
        "days_expired": "Days left: ⚠️ Expired",
        "devices": "Devices: 📱 {}",
        "config_header": "🔐 **Config for `{}`**\n",
        "config_body": "`{}`",
        "qr_caption": "📱 QR Code for {} on {}",
        "admin_promoted": "✅ Server '{}' added.\nYou have been promoted to admin.",
        "admin_denied": "⛔ Admin access required.",
        "usage": "Usage: {}",
        "user_created": "✅ User '{}' created on {}\n\n🔐 Config:\n`{}`",
        "user_removed": "✅ User '{}' revoked on {}.",
        "user_suspended": "⏸️ User '{}' suspended on {}.",
        "user_unsuspended": "✅ User '{}' unsuspended on {}.",
        "user_extended": "✅ User '{}' extended by {} days on {}.",
        "broadcast_sent": "📢 Broadcast sent to {} users.",
    },
    "fa": {
        "welcome": "👋 به بات XHTTP خوش آمدید!\n\nبرای اتصال حساب خود از /link استفاده کنید.",
        "not_linked": "❌ شما متصل نیستید. ابتدا از /link استفاده کنید.",
        "already_linked": "✅ شما به عنوان `{}` متصل شده‌اید. برای تغییر از /unlink استفاده کنید.",
        "link_success": "✅ به `{}` متصل شدید.",
        "unlink_success": "✅ اتصال قطع شد.",
        "no_servers": "⚠️ هیچ سروری تنظیم نشده است. با مدیر تماس بگیرید.",
        "servers_list": "🖥 **سرورهای تحت نظارت:**\n{}",
        "language_changed": "✅ زبان به فارسی تنظیم شد.",
        "usage_header": "📊 **وضعیت کاربری `{}`**\n",
        "no_account": "❌ حسابی یافت نشد.",
        "error": "⚠️ خطا: {}",
        "status_active": "✅ فعال",
        "status_suspended": "⏸️ متوقف",
        "status_revoked": "🚫 لغو شده / منقضی",
        "data_label": "حجم: {} `{:.1f} گیگ / {:.1f} گیگ` ({:.1f}٪)",
        "data_unlimited": "حجم: ♾️ نامحدود",
        "days_left": "روزهای باقی‌مانده: 📅 {} روز",
        "days_expired": "روزهای باقی‌مانده: ⚠️ منقضی شده",
        "devices": "دستگاه‌ها: 📱 {}",
        "config_header": "🔐 **کانفیگ برای `{}`**\n",
        "config_body": "`{}`",
        "qr_caption": "📱 کد QR برای {} در سرور {}",
        "admin_promoted": "✅ سرور '{}' اضافه شد.\nشما به مدیر ارتقا یافتید.",
        "admin_denied": "⛔ دسترسی فقط برای مدیران.",
        "usage": "طریقه استفاده: {}",
        "user_created": "✅ کاربر '{}' در {} ایجاد شد.\n\n🔐 کانفیگ:\n`{}`",
        "user_removed": "✅ کاربر '{}' در {} لغو شد.",
        "user_suspended": "⏸️ کاربر '{}' در {} متوقف شد.",
        "user_unsuspended": "✅ کاربر '{}' در {} فعال شد.",
        "user_extended": "✅ کاربر '{}' به مدت {} روز در {} تمدید شد.",
        "broadcast_sent": "📢 پیام به {} کاربر ارسال شد.",
    }
}

def get_text(key: str, lang: str = "en", **kwargs) -> str:
    text = STRINGS.get(lang, STRINGS["en"]).get(key, key)
    return text.format(**kwargs) if kwargs else text
